server:
  port: 9528

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: Redis
          uri: lb://redis-service-providers
          predicates:
            - Path=/redis/**
          filters:
            - Token
            - StripPrefix=1
            - PrefixPath=/redisprovider
