server:
  port: 9528

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 159.89.156.59:8848
    gateway:
      routes:
        - id: consumer
          uri: lb://nacos-consumer
          predicates:
            - Path=/consumer/**
