server:
  port: 8889

spring:
  application:
    name: token-intercepter
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

filter-config:
  use-token: true
  token-match: /test