server:
  port: 8081

spring:
  application:
    name: redis-consumer
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
