spring:
  # 适应异常捕捉
  mvc:
    throw-exception-if-no-handler-found: true
  #未找到路径时抛出异常
  resources:
    add-mappings: false
  # 配置数据库
  datasource:
    # username: root
    username: GTzXAawuB2lELEUr(7tYsyjMCmmuDn2OboBM7+rhO65eiNTBybQSl+9d4FACleSoHaXfoXlfO8x2edxQ/)
    # password: 284317
    password: GTzXAawuB2lELEUr(E7ENA7UpCRl438nchqyK4cnLomHA5VQqZ8RlCut28sszcra3UKSd2tFD6jqHZ300)
    # 针对mysql8 确保数据库存在 使用gmt时区
    # url: jdbc:mysql://localhost:3306/mangolee?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    url: GTzXAawuB2lELEUr(8iu7nQhtjDzCeQBrP/hw7t/0VvqtbKfGeqKeXzKwtStzeOWFMNGZNey0NexrNr8mjVUkSfLP72rhunzUMs4wHLSh334naWc0i00PbeCE2jNx64qRzQzmor51Yc08G6jpN+Pp7W5ImnxKM3vg93fkysDB0e0aOPPGY3+WDspbL6RhrAPXU+kOJsYsFQXTHTZl)
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # username: root
      username: GTzXAawuB2lELEUr(7dQw5+3ISurts7fQq2UKgIlq9vLRqXI+08qPKuMPdQRqVWa6Gn1pBtYEhRd6PuRb)
      # password: 284317
      password: GTzXAawuB2lELEUr(dwoK6Vz31vcgGSz3WYauiFnrNp6FCNH5tvHEonIP9JkInf2q/uOz4s/LTy9ylzZZ)
      # url: jdbc:mysql://localhost:3306/mangolee?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      url: GTzXAawuB2lELEUr(dz/IO9a6rGoFKXTRV+ZGBlkkip3dCTuN/nbNc18pwmb6s0wgD5C+9oyQZAYt2sTZLtu43wqxKavDcB+IVyK+IxMbM9wG2XkcGT9C5CZILv6tTqpuy8ovz5z56f3Vsg66Rir1699uMHr3yt8DnBIpQMPLCRUIbmgXtj4WlP4JP5oGvl6kaU5gK4o+LxejQimI)
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 8
      max-active: 16
      min-idle: 1
      # 获取连接等待超时的时间
      max-wait: 60000
      # 打开强制回收连接功能
      remove-abandoned: true
      # 超时时间
      remove-abandoned-timeout-millis: 600000
      # 连接回收时记录日志
      log-abandoned: true
      # 采集 web-jdbc 关联监控的数据
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "/druid/*"
      # 展示 Druid 的统计信息
      stat-view-servlet:
        enabled: true
        # login-username: admin
        login-username: GTzXAawuB2lELEUr(PloOnXJSbNHkGX3ZFVXu17ro933GMkg/URFb76v2/pYlGvqLXwu+UsE1ecV9S17s)
        # login-password: 123456
        login-password: GTzXAawuB2lELEUr(uZQa3YXU53cUBzN/I4og6xqKOdQ1zILCj0CtC0Md9w/iyfAp4QT3IuHzcae+Sh+7)
        reset-enable: true
        url-pattern: /druid/*
    # 初始化数据库
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  # 配置文件编码
  mandatory-file-encoding: utf-8
  # 配置redis
  redis:
    #修改为自己的redis地址， 需要提前对redis配置文件进行修改
    #如果需要远程调试 先进行ssh端口转发到本地12345
    host: localhost
    port: 12345
    #确定auth模块使用的数据库编号
    database: 0
    #连接超时时间（毫秒
    timeout: 1000
  cloud:
    # 配置nacos
    nacos:
      discovery:
        server-addr: localhost:8848
        service: authorization
  application:
    name: authorization
  # 配置热部署
  devtools:
    livereload:
      port: 40000

# 配置mybatisplus
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml

# 配置tomcat端口号
server:
  port: 8080

#filter-config:
#  use-token: true