

spring:
  # 配置数据库
  datasource:
    username: root
    password: 284317
    # 针对mysql8 确保数据库存在 使用gmt时区
    url: jdbc:mysql://localhost:3306/mangolee?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: 284317
      url: jdbc:mysql://localhost:3306/mangolee?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 8
      max-active: 16
      min-idle: 1
      # 获取连接等待超时的时间
      max-wait: 60000
      # 打开强制回收连接功能
      remove-abandoned: true
      # 超时时间
      remove-abandoned-timeout-millis: 600000
      # 连接回收时记录日志
      log-abandoned: true
      # 采集 web-jdbc 关联监控的数据
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "/druid/*"
      # 展示 Druid 的统计信息
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: true
        url-pattern: /druid/*
    # 初始化数据库
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  # 配置文件编码
  mandatory-file-encoding: utf-8
  # 配置redis
  redis:
    #修改为自己的redis地址， 需要提前对redis配置文件进行修改
    #如果需要远程调试 先进行ssh端口转发到本地12345
    host: localhost
    port: 12345
    #port: 6379
    #使用数据库
    database: 0
    #连接超时时间（毫秒
    timeout: 1000

# 配置mybatisplus
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml

# 配置tomcat端口号
server:
  port: 8080